---
java_jdk_version: 11.0.11
java_oracle_jdk_package: jdk-11.0.11_linux-x64_bin.tar.gz

elastic_version: "7.10.1"
elastic_package: elasticsearch-7.10.1-linux-x86_64.tar.gz
elastic_home: "/opt/elastic/{{ elastic_version }}"

kibana_version: "7.16.3"
kibana_package: kibana-7.16.3-linux-x86_64.tar.gz
kibana_home: "/opt/kibana/{{ kibana_version }}"


