---
  - src: git@github.astorf15/kibana-role.git
    scm: git
    version: "1.0"
    name: kibana-role 
  - src: git@github.com:astorf15/elastic-role.git
    scm: git
    version: "1.0"
    name: elastic-role
  - src: git@github.com:astorf15/java-role.git
    scm: git
    version: "1.0"
    name: java-role 