galaxy_info:
  author: astorf15
  description: Install elasticsearch from remote host
  company: Netology
  license: BSD-3-Clause
  min_ansible_version: "2.8"
  platforms:
  - name: Ubuntu
  - name: EL
     