version: "3.9"

services:
  dind:
    image: docker:20-dind
    container_name: dind
    restart: always
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      - --storage-driver=overlay2

  runner:
    restart: always
    image: gitlab/gitlab-runner
    container_name: runner
    depends_on:
      - dind
    environment:
      - DOCKER_HOST=tcp://dind:2375
    volumes:
      - ./runner_config:/etc/gitlab-runner:z

  register-runner:
    restart: 'no'
    image: gitlab/gitlab-runner
    depends_on:
      - dind
    environment:
      - CI_SERVER_URL=http://gitlab.rusdevops.ru/
      - REGISTRATION_TOKEN=GR1348941y_N1fzaZnoXB21FyR8nE
    command:
      - register
      - --non-interactive
      - --locked=false
      - --name=runner
      - --executor=docker
      - --docker-image=docker:20-dind
      - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock
    volumes:
      - ./runner_config:/etc/gitlab-runner:z